/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooq.tables.records;


import com.example.demo.jooq.tables.RevokedTokens;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RevokedTokensRecord extends UpdatableRecordImpl<RevokedTokensRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.revoked_tokens.id</code>.
     */
    public RevokedTokensRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.revoked_tokens.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.revoked_tokens.jti</code>.
     */
    public RevokedTokensRecord setJti(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.revoked_tokens.jti</code>.
     */
    public String getJti() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.revoked_tokens.revoked_at</code>.
     */
    public RevokedTokensRecord setRevokedAt(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.revoked_tokens.revoked_at</code>.
     */
    public OffsetDateTime getRevokedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.revoked_tokens.reason</code>.
     */
    public RevokedTokensRecord setReason(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.revoked_tokens.reason</code>.
     */
    public String getReason() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.revoked_tokens.created_by_user_id</code>.
     */
    public RevokedTokensRecord setCreatedByUserId(UUID value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.revoked_tokens.created_by_user_id</code>.
     */
    public UUID getCreatedByUserId() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RevokedTokensRecord
     */
    public RevokedTokensRecord() {
        super(RevokedTokens.REVOKED_TOKENS);
    }

    /**
     * Create a detached, initialised RevokedTokensRecord
     */
    public RevokedTokensRecord(UUID id, String jti, OffsetDateTime revokedAt, String reason, UUID createdByUserId) {
        super(RevokedTokens.REVOKED_TOKENS);

        setId(id);
        setJti(jti);
        setRevokedAt(revokedAt);
        setReason(reason);
        setCreatedByUserId(createdByUserId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RevokedTokensRecord
     */
    public RevokedTokensRecord(com.example.demo.jooq.tables.pojos.RevokedTokens value) {
        super(RevokedTokens.REVOKED_TOKENS);

        if (value != null) {
            setId(value.getId());
            setJti(value.getJti());
            setRevokedAt(value.getRevokedAt());
            setReason(value.getReason());
            setCreatedByUserId(value.getCreatedByUserId());
            resetChangedOnNotNull();
        }
    }
}
