/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooq.tables.daos;


import com.example.demo.jooq.tables.Roles;
import com.example.demo.jooq.tables.records.RolesRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class RolesDao extends DAOImpl<RolesRecord, com.example.demo.jooq.tables.pojos.Roles, UUID> {

    /**
     * Create a new RolesDao without any configuration
     */
    public RolesDao() {
        super(Roles.ROLES, com.example.demo.jooq.tables.pojos.Roles.class);
    }

    /**
     * Create a new RolesDao with an attached configuration
     */
    @Autowired
    public RolesDao(Configuration configuration) {
        super(Roles.ROLES, com.example.demo.jooq.tables.pojos.Roles.class, configuration);
    }

    @Override
    public UUID getId(com.example.demo.jooq.tables.pojos.Roles object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.demo.jooq.tables.pojos.Roles> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Roles.ROLES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.demo.jooq.tables.pojos.Roles> fetchById(UUID... values) {
        return fetch(Roles.ROLES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.demo.jooq.tables.pojos.Roles fetchOneById(UUID value) {
        return fetchOne(Roles.ROLES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.example.demo.jooq.tables.pojos.Roles> fetchOptionalById(UUID value) {
        return fetchOptional(Roles.ROLES.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.demo.jooq.tables.pojos.Roles> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Roles.ROLES.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.example.demo.jooq.tables.pojos.Roles> fetchByName(String... values) {
        return fetch(Roles.ROLES.NAME, values);
    }

    /**
     * Fetch a unique record that has <code>name = value</code>
     */
    public com.example.demo.jooq.tables.pojos.Roles fetchOneByName(String value) {
        return fetchOne(Roles.ROLES.NAME, value);
    }

    /**
     * Fetch a unique record that has <code>name = value</code>
     */
    public Optional<com.example.demo.jooq.tables.pojos.Roles> fetchOptionalByName(String value) {
        return fetchOptional(Roles.ROLES.NAME, value);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.demo.jooq.tables.pojos.Roles> fetchRangeOfCreatedAt(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Roles.ROLES.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.example.demo.jooq.tables.pojos.Roles> fetchByCreatedAt(OffsetDateTime... values) {
        return fetch(Roles.ROLES.CREATED_AT, values);
    }
}
