/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooq.tables.daos;


import com.example.demo.jooq.tables.UserRoles;
import com.example.demo.jooq.tables.records.UserRolesRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class UserRolesDao extends DAOImpl<UserRolesRecord, com.example.demo.jooq.tables.pojos.UserRoles, Record2<UUID, UUID>> {

    /**
     * Create a new UserRolesDao without any configuration
     */
    public UserRolesDao() {
        super(UserRoles.USER_ROLES, com.example.demo.jooq.tables.pojos.UserRoles.class);
    }

    /**
     * Create a new UserRolesDao with an attached configuration
     */
    @Autowired
    public UserRolesDao(Configuration configuration) {
        super(UserRoles.USER_ROLES, com.example.demo.jooq.tables.pojos.UserRoles.class, configuration);
    }

    @Override
    public Record2<UUID, UUID> getId(com.example.demo.jooq.tables.pojos.UserRoles object) {
        return compositeKeyRecord(object.getUserId(), object.getRoleId());
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.demo.jooq.tables.pojos.UserRoles> fetchRangeOfUserId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(UserRoles.USER_ROLES.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.example.demo.jooq.tables.pojos.UserRoles> fetchByUserId(UUID... values) {
        return fetch(UserRoles.USER_ROLES.USER_ID, values);
    }

    /**
     * Fetch records that have <code>role_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.demo.jooq.tables.pojos.UserRoles> fetchRangeOfRoleId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(UserRoles.USER_ROLES.ROLE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.example.demo.jooq.tables.pojos.UserRoles> fetchByRoleId(UUID... values) {
        return fetch(UserRoles.USER_ROLES.ROLE_ID, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.demo.jooq.tables.pojos.UserRoles> fetchRangeOfCreatedAt(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(UserRoles.USER_ROLES.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.example.demo.jooq.tables.pojos.UserRoles> fetchByCreatedAt(OffsetDateTime... values) {
        return fetch(UserRoles.USER_ROLES.CREATED_AT, values);
    }
}
