/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRoles implements Serializable {

    private static final long serialVersionUID = 1L;

    private final UUID userId;
    private final UUID roleId;
    private final OffsetDateTime createdAt;

    public UserRoles(UserRoles value) {
        this.userId = value.userId;
        this.roleId = value.roleId;
        this.createdAt = value.createdAt;
    }

    public UserRoles(
        UUID userId,
        UUID roleId,
        OffsetDateTime createdAt
    ) {
        this.userId = userId;
        this.roleId = roleId;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.user_roles.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.user_roles.role_id</code>.
     */
    public UUID getRoleId() {
        return this.roleId;
    }

    /**
     * Getter for <code>public.user_roles.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserRoles other = (UserRoles) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.roleId == null) {
            if (other.roleId != null)
                return false;
        }
        else if (!this.roleId.equals(other.roleId))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.roleId == null) ? 0 : this.roleId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserRoles (");

        sb.append(userId);
        sb.append(", ").append(roleId);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
